### ISSUE TITLE
 this problems also occured

### ISSUE THREAD

**Issue by superJack2222** [Z-Zheng/ever#3]
module 'ever' has no attribute 'viz'

**Comment by Z-Zheng** [comment]
The sub-package 'viz' is temporarily unsupported in 'ever'.

**Comment by zts12** [comment]
![联想截图_20240326155849](https://github.com/Z-Zheng/ever/assets/156739265/98be1ba2-a2ec-48d3-a371-edad10fde820)
I also encountered the same problem, there is no viz in the ever library.May I ask how to solve it?

**Comment by Z-Zheng** [comment]
> ![联想截图_20240326155849](https://private-user-images.githubusercontent.com/156739265/316774459-98be1ba2-a2ec-48d3-a371-edad10fde820.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDEzNzUsIm5iZiI6MTcxMTQ0MTA3NSwicGF0aCI6Ii8xNTY3MzkyNjUvMzE2Nzc0NDU5LTk4YmUxYmEyLWEyZWMtNDhkMy1hMzcxLWVkYWQxMGZkZTgyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwODE3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjBkYTcwMTg4NzQzMjY5OWFiYzc0OWE3NWQ5MDQ3YWNkNDdkYjFmNTE5YTlmYmJmYWJkZmUzMWI2MDFmNDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PgVL9Yg34fF0UbDo3KmzZYmVZza68JUDh8lyoXiPxzw) I also encountered the same problem, there is no viz in the ever library.May I ask how to solve it?

comment any codes related to viz.
The viz sub-package is not included in the open-source version of ever, and it has been removed due to compatibility.
