### ISSUE TITLE
你好，报错ModuleNotFoundError: No module named 'data'

### ISSUE THREAD

**Issue by Sacrificeljj** [Z-Zheng/ever#4]
![IMG_0162(20221001-134602)](https://user-images.githubusercontent.com/97828326/193394656-4bdc4cdc-d5af-4d4f-90a1-a9d7af458cb6.PNG)

**Comment by Maschinist-LZY** [comment]
> ![IMG_0162(20221001-134602)](https://user-images.githubusercontent.com/97828326/193394656-4bdc4cdc-d5af-4d4f-90a1-a9d7af458cb6.PNG)

请问您怎么解决的呢
