### ISSUE TITLE
No module named 'ever.data.dataset'

### ISSUE THREAD

**Issue by xxxxxxx526** [Z-Zheng/ever#5]
Hello, when I import ever, it got "ModuleNotFoundError: No module named 'ever.data.dataset'". I found that the dataset file is indeed not in the data file. How can I solve this problem?

**Comment by Z-Zheng** [comment]
Thanks for your feedback. i have fixed this problem. you can update ever via pip install --upgrade git+https://github.com/Z-Zheng/ever.git

**Comment by xxxxxxx526** [comment]
Thank you very much！
