### ISSUE TITLE
POP-NET

### ISSUE THREAD

**Issue by a987042035** [Z-Zheng/ever#6]
您好师兄，很高兴能够看到您2019年在IEEE的文章POP-NET: ENCODER-DUAL DECODER FOR SEMANTIC SEGMENTATION AND SINGLE-VIEW HEIGHT ESTIMATION，我感触颇深，但是您提供的GitHub开源代码失效了，可以重新发我一份吗，我想学习一下，十分感谢您的解答，祝您生活愉快 学业顺利！

**Comment by Sunny-Yu225** [comment]
您好师兄，看了您这篇文章《Unifying remote sensing change detection via deep probabilistic change models: From principles, models to applications》，受益颇丰，想问您是否有train.py文件，是否可以在空闲时间发我一份，我想学习一下，十分感谢您的解答，祝您学业顺利，生活愉快

**Comment by Z-Zheng** [comment]
感谢关注！变化检测相关资源的发布请查看https://github.com/Z-Zheng/pytorch-change-models ，所提到的工作是用ever训练的，只要有ERModule和ERDataset的实现就可以直接训练；然后changesparse内的ERModule实现已在https://github.com/Z-Zheng/pytorch-change-models/blob/main/torchange/models/changesparse.py 包含；抱歉暂时没有时间撰写文档，完整的指南会随着torchange的开发逐步完善 @Sunny-Yu225

**Comment by Sunny-Yu225** [comment]
> 感谢关注！变化检测相关资源的发布请查看 https://github.com/Z-Zheng/pytorch-change-models ，所提到的工作是用ever训练的，只要有ERModule和ERDataset的实现就可以直接训练;然后changesparse内的ERModule实现已在 https://github.com/Z-Zheng/pytorch-change-models/blob/main/torchange/models/changesparse.py 包含;抱歉暂时没有时间撰写文档，完整的指南会随着torchange的开发逐步完善

谢谢师兄答疑，祝您工作顺利，生活愉快！！
